default: main

#CXX = ${KOKKOS_PATH}/bin/nvcc_wrapper -x cu -ccbin `which mpic++`
#LINK = ${CXX}
## CFLAGS = -DARRAY_DEBUG -O1 -g -I${PNETCDF_PATH}/include

#KOKKOS_DEVICES = "Cuda"

# Specify the GPU architecture
# See https://github.com/kokkos/kokkos/wiki/Compiling#table-43-architecture-variables
#KOKKOS_ARCH = "Ampere80"
#KOKKOS_ARCH = "Volta70"
#KOKKOS_ARCH = "Maxwell50"
#KOKKOS_ARCH = "Pascal61"
#KOKKOS_OPTIONS += "disable_profiling"
#KOKKOS_CUDA_OPTIONS += "enable_lambda"
#KOKKOS_DEBUG=yes

#DEPFLAGS = -M
#OBJ = $(BIN_DIR)/$(notdir $(SRC:.cpp=.o))
#LIB =

include ${KOKKOS_PATH}/Makefile.kokkos

main: $(EXE)

$(EXE): $(OBJ) $(KOKKOS_LINK_DEPENDS)
	$(LINK) $(KOKKOS_LDFLAGS) $(EXTRA_PATH) $(OBJ) $(KOKKOS_LIBS) $(LIB) -o $(EXE) $(LDFLAGS)

$(BIN_DIR)/%.o:%.cpp $(KOKKOS_CPP_DEPENDS) *.h
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) $(EXTRA_INC) -c $< -o $@

$(UNITTESTS): $(OBJ_UT) $(KOKKOS_LINK_DEPENDS)
	$(LINK) $(KOKKOS_LDFLAGS) $(EXTRA_PATH) $(OBJ_UT) $(KOKKOS_LIBS) $(LIB) -o $(UNITTESTS) $(LDFLAGS)

$(BIN_DIR_UT)/%.o: unitTests/%.cpp $(KOKKOS_CPP_DEPENDS) *.h
	$(CXX) $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) $(CXXFLAGS) $(EXTRA_INC) -c $< -o $@
